"""Property-based tests for task/flow_recorder.py -- FlowRecorder.

# Feature: cv-desktop-automation-agent, Property 13: 录制结果符合 Flow_Template JSON Schema
"""

from __future__ import annotations

import json
import tempfile
from pathlib import Path
from typing import Any
from unittest.mock import patch

import jsonschema
import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

from task.flow_recorder import FlowRecorder

# ---------------------------------------------------------------------------
# Load the JSON Schema once for reuse across all tests
# ---------------------------------------------------------------------------

_SCHEMA_PATH = Path(__file__).parent.parent.parent / "task" / "schema" / "flow_template.schema.json"
with _SCHEMA_PATH.open(encoding="utf-8") as _fh:
    _FLOW_SCHEMA: dict[str, Any] = json.load(_fh)


# ---------------------------------------------------------------------------
# Hypothesis strategies for generating synthetic input events
# ---------------------------------------------------------------------------

_COORD = st.integers(min_value=0, max_value=3840)

_mouse_move_event = st.builds(
    lambda x, y: ("mouse_move", x, y),
    x=_COORD,
    y=_COORD,
)

_mouse_click_event = st.builds(
    lambda x, y: ("mouse_click", x, y),
    x=_COORD,
    y=_COORD,
)

_key_press_event = st.builds(
    lambda k: ("key_press", k),
    k=st.sampled_from(["enter", "space", "tab", "escape", "ctrl", "shift", "alt", "backspace"]),
)

_type_text_event = st.builds(
    lambda c: ("type_text", c),
    c=st.text(
        alphabet=st.characters(
            whitelist_categories=("Lu", "Ll", "Nd"),
            whitelist_characters="!@#$%^&*()-_=+[]{}|;:',.<>?/`~",
        ),
        min_size=1,
        max_size=20,
    ),
)

_event_strategy = st.one_of(
    _mouse_move_event,
    _mouse_click_event,
    _key_press_event,
    _type_text_event,
)

_event_sequence = st.lists(_event_strategy, min_size=0, max_size=30)


# ---------------------------------------------------------------------------
# Helper: inject events into a started recorder
# ---------------------------------------------------------------------------

def _inject_events(recorder: FlowRecorder, events: list[tuple[Any, ...]]) -> None:
    """Replay a list of synthetic events into the recorder's internal handlers."""
    from pynput.keyboard import Key, KeyCode
    from pynput.mouse import Button

    for event in events:
        kind = event[0]
        if kind == "mouse_move":
            _, x, y = event
            recorder._on_mouse_move(x, y)
        elif kind == "mouse_click":
            _, x, y = event
            recorder._on_mouse_click(x, y, Button.left, pressed=True)
        elif kind == "key_press":
            _, key_name = event
            key = getattr(Key, key_name, None)
            if key is not None:
                recorder._on_key_press(key)
        elif kind == "type_text":
            _, text = event
            for char in text:
                recorder._on_key_press(KeyCode.from_char(char))


# ---------------------------------------------------------------------------
# Property 13: 录制结果符合 Flow_Template JSON Schema
# ---------------------------------------------------------------------------

@settings(max_examples=100)
@given(events=_event_sequence, session_name=st.text(min_size=1, max_size=50, alphabet=st.characters(whitelist_categories=("Lu", "Ll", "Nd"), whitelist_characters="_-")))
def test_property_13_recorded_json_validates_against_schema(
    events: list[tuple[Any, ...]],
    session_name: str,
) -> None:
    """Property 13: 录制结果符合 Flow_Template JSON Schema

    **Validates: Requirements 8.2, 8.3**

    For any recording session producing a sequence of operation events,
    the JSON file generated by FlowRecorder.stop() must pass validation
    against flow_template.schema.json, and each step must contain
    step_id, action_type, parameters, delay_ms fields.
    """
    # Feature: cv-desktop-automation-agent, Property 13: 录制结果符合 Flow_Template JSON Schema

    recorder = FlowRecorder()

    with tempfile.TemporaryDirectory() as tmp:
        with (
            patch("task.flow_recorder.mouse.Listener"),
            patch("task.flow_recorder.keyboard.Listener"),
            patch("task.flow_recorder.RECORDINGS_DIR", Path(tmp)),
        ):
            recorder.start(session_name)
            _inject_events(recorder, events)
            file_path = recorder.stop()

        # Read the generated JSON
        with open(file_path, encoding="utf-8") as fh:
            data = json.load(fh)

    # 1. Must pass JSON Schema validation
    jsonschema.validate(instance=data, schema=_FLOW_SCHEMA)

    # 2. Top-level required fields must be present
    assert "version" in data
    assert "name" in data
    assert "created_at" in data
    assert "steps" in data
    assert isinstance(data["steps"], list)

    # 3. Each step must contain the four required fields
    for step in data["steps"]:
        assert "step_id" in step, f"step missing step_id: {step}"
        assert "action_type" in step, f"step missing action_type: {step}"
        assert "parameters" in step, f"step missing parameters: {step}"
        assert "delay_ms" in step, f"step missing delay_ms: {step}"

        # step_id must be a positive integer
        assert isinstance(step["step_id"], int) and step["step_id"] >= 1

        # action_type must be one of the allowed enum values
        assert step["action_type"] in {"mouse_click", "mouse_move", "key_press", "type_text"}

        # parameters must be a dict
        assert isinstance(step["parameters"], dict)

        # delay_ms must be a non-negative integer
        assert isinstance(step["delay_ms"], int) and step["delay_ms"] >= 0

    # 4. step_ids must be sequential starting from 1
    if data["steps"]:
        ids = [s["step_id"] for s in data["steps"]]
        assert ids == list(range(1, len(ids) + 1)), f"step_ids not sequential: {ids}"
